Master
tvigon/widergy-mobile-training pull request #1
Opened 2021-09-08 20:27 UTC by tvigon

2021-09-10 14:35 UTC, tvigon commented
No psa nada

2021-09-10 19:14 UTC, lucawidergy requested changes

2021-09-10 19:14 UTC, lucawidergy commented on App.js
> +        <CalcButtons
calc buttons y opCalcButtons deberian ser el mismo componente, fijate que reciben las mismas props solo que valores distintos.

2021-09-10 19:14 UTC, lucawidergy commented on App.js
> +          {error}
error || aux || value

2021-09-10 19:14 UTC, lucawidergy commented on App.js
> +  const [aux, setAux] = useState('');
nombre mas representativo

2021-09-10 19:14 UTC, lucawidergy commented on components/CalcButtons.js
> +              switch (selectedAux.slice(-1)) {
en general no usamos switchs y usamos diccionarios/ tablas de busqueda. 

ademas que toda esta logica dentro de onPress es un choclo. Un par de cosas que mencionar aca:

1- en todo caso deberias declarar una funcion y y pasarsela al onPRess porque sino molesta mucho a la lectura del componente ademas. Hay q tratar de modularizar estas cosas.
2- el onPress en realidad deberia recibirlo CalcButtons de afuera y esta logica no esta aca ya que un boton solo ejecuta una accion.

2021-09-10 19:14 UTC, lucawidergy commented on components/CalcButtons.js
> +              switch (selectedAux.slice(-1)) {
Por otro lado, lo ideal seria tener una tabla de busqueda del tipo:

ACTIONS_BUTTONS: [
{
label: '+ '
style: {estilos del boton por ejemplo},
action: setValue
},
{
label: '- '
style: {estilos del boton por ejemplo},
action: setValue
}


]

2021-09-10 19:14 UTC, lucawidergy commented on components/CalcButtons.js
> +              switch (selectedAux.slice(-1)) {
idealmente seria que trabajes con todo un string, y se parcee y calcule al momento de apretar igual. Por ejemplo vos podes tener definidas las funciones de los operadores entre 2 numeros e ir parseando acumulando y resolviendo todo. Esto si queres lo podemos charlar juntos

2021-09-10 19:14 UTC, lucawidergy commented on components/OpCalcButtons.js
> +          if (
cuando veas que tenes asi condiciones super particulare duda. Si esto es para colocar el numero negativo lo ideal es que eso lo checkees cuando parseas la operacion como te puse arriba

2021-09-10 19:18 UTC, lucawidergy commented on App.js
> +        <CalcButtons
generalmente, la api de un boton va a tener label, onPress, disabled y a lo sumo style

2021-09-10 20:45 UTC, lcastelloni requested changes
Abajo te dejo una comentarios sobre el funcionamiento:

- Al principio si abro la app y presiono "-" la expresion queda como "0 - ..."
![image](https://user-images.githubusercontent.com/69810317/132914959-110c716d-25d9-4e98-96fe-4442e079f6a4.png)
- Si apretas cualquiera de las operaciones y decidis cambiarla te tendria que dejar. SIempre y cuuando no haya ingresado algun numero
![image](https://user-images.githubusercontent.com/69810317/132915012-03035d74-bc3c-4038-8508-6ad33d634c0f.png)
- El punto solo te deja ponerlo si ya existe otro numero adelante. Tendria que dejar ponerte ".15" y que lo tome como un 0.15
- Si por ejemplo el usuario quiere poner "4x4x4" no te deja. Tenes que hacer 4x4 y apretar igual y despues hacer el resultado por 4. Podriamos hacer que al hacer "4x4" y al apretar "-" o cualquier otra operacion en la pantalla quede "16-..."

2021-09-17 16:02 UTC, lcastelloni requested changes
Check my comments

2021-09-17 16:02 UTC, lcastelloni commented on App.js
> +      if (
Move this to a utils.js file. Inside utils.js we try to put all the functions that we use and are long to keep the code inside the component as clean and readable as possible

2021-09-17 16:02 UTC, lcastelloni commented on App.js
> +  } else if (val.length === 0){return val;}
The same with this function

2021-09-17 16:02 UTC, lcastelloni commented on App.js
> +  {label: '4', onPress: () => {setVal(prevValue => numButton(prevValue, '4'));}},
Here we we are repeating a lot of code. We could could do as follow:

```suggestion
const getScreenButtons = setVal => [
  {label: '7', onPress: () => {setVal(prevValue => numButton(prevValue, '7'));}},
  {label: '8', onPress: () => {setVal(prevValue => numButton(prevValue, '8'));}},
  {label: '9', onPress: () => {setVal(prevValue => numButton(prevValue, '9'));}},
  {label: '4', onPress: () => {setVal(prevValue => numButton(prevValue, '4'));}},
```
```suggestion
const getScreenButtons = (value, setVal, operation) => [
  {label: value, onPress: () => {setVal(prevValue => operation(prevValue, value));}},
```

2021-09-17 16:03 UTC, lcastelloni commented on styles.js
> +    //estos numeros son re magicos dentro de calc butons
delete comment

2021-09-17 17:21 UTC, lucawidergy requested changes
is working weirdly. No operation should be done until the =  is pressed. In fact, this is how different things are showing on the display once the equal is pressed

2021-09-17 17:21 UTC, lucawidergy commented on App.js
> +    if (
i dont like this. multiple if and special conditions are not good

2021-09-17 17:21 UTC, lucawidergy commented on App.js
> +          {SCREEN_BUTTONS.splice(0, 5).map(button => renderButtons(button, false))}
i prefer you separate this in two objects and not splice a bigone

2021-09-17 17:21 UTC, lucawidergy commented on components/CalcButtons.js
> +              switch (selectedAux.slice(-1)) {
Why this still here?

2021-09-17 17:21 UTC, lucawidergy commented on components/OpCalcButtons.js
> +          if (
why this still here?

2021-09-17 17:21 UTC, lucawidergy commented on App.js
> +const renderButtons = (button, useNumericalStyle ) => (
here should have a component for your button!

2021-09-21 14:15 UTC, lcastelloni requested changes
Check my comments

2021-09-21 14:15 UTC, lcastelloni commented on screens/HistoryScreen.js
> +    <Text style={{alignSelf: 'center', fontSize: 30}}>{text}</Text>
in styles.js file

2021-09-21 14:15 UTC, lcastelloni commented on screens/HistoryScreen.js
> +    <View style={{flex: 1}}>
Move to styles.js

2021-09-21 14:15 UTC, lcastelloni commented on screens/HistoryScreen.js
> +  const {logValue} = route.params;
remove this. This screen will be empty for the moment. It just needs a go back button (you have already done that)

2021-09-21 17:38 UTC, lucawidergy requested changes
much better. Check the code comments. About functionality:

* i cant put a - in the firts number also i cant do  1 -- 1 
* history is not showing nothing.
* you have two back buttons doing the same :thinking:

2021-09-21 17:38 UTC, lucawidergy commented on screens/HistoryScreen.js
> +import styles from '../styles';
the folder structure is screens -> HistoryScreen -> index.js! also you need a style file only for this screen.

2021-09-21 17:38 UTC, lucawidergy commented on screens/HomeScreen.js
> +const HomeScreen = ({navigation}) => {
same folder structure comment

2021-09-21 17:38 UTC, lucawidergy commented on screens/HomeScreen.js
> +  const numArray = ['7', '8', '9', '4', '5', '6', '1', '2', '3', '0'];
this is a constant. should stay in constants file and UPPERCASE and snake_case

2021-09-21 17:38 UTC, lucawidergy commented on screens/HomeScreen.js
> +    <TouchableOpacity onPress={press} onLongPress={longPress} style={style}>
and the button component we have talk?

2021-09-21 17:38 UTC, lucawidergy commented on screens/HomeScreen.js
> +  const OP_NUM_BUTT = getOpNumButt(setValue);
op num but? please put better names

2021-09-21 17:38 UTC, lucawidergy commented on screens/HomeScreen.js
> +            renderButtons(
no, this is not what we talking yesterday

2021-09-21 17:38 UTC, lucawidergy commented on screens/HomeScreen.js
> +        <TouchableOpacity
if you make a button component you could reuse it here

2021-09-21 17:38 UTC, lucawidergy commented on styles.js
> +const styles = StyleSheet.create({
please make a style for each component or screen

2021-09-21 17:38 UTC, lucawidergy commented on utils.js
> +  let firstRegex = /[-]?[.]?[0-9]*[.]?[0-9]+[/x][.]?[0-9]*[.]?[0-9]+/g;
better names for this variables? also they are const

2021-09-22 19:44 UTC, lucawidergy requested changes
Check the comments and the comment of the last corrections again!

2021-09-22 19:44 UTC, lucawidergy commented on components/CalcButtons.js
> +      style ? [homeStyles.row, homeStyles.numButtons] : [homeStyles.opsStyle]
style is not a boolean, is the style object.

2021-09-22 19:44 UTC, lucawidergy commented on components/CalcButtons.js
> +const MyButton = ({label, press, style, longPress}) => (
no, this is  the button  component and should be a separated file

2021-09-22 19:44 UTC, lucawidergy commented on components/CalcButtons.js
> +export {CalcButtons, MyButton};
always only one export!

2021-09-22 19:44 UTC, lucawidergy commented on components/CalcButtons.js
> +    {arrayButt.map(button => (
this shouldn't be here Calbutton or my button should be the button that you can re use. but this second one Calbutton has not sense to be a separated component. this logic it was already correctly before

2021-09-22 19:44 UTC, lucawidergy commented on screens/HistoryScreen/index.js
> +      <ScrollView style={historyStyles.container} />
empty scroll view? wheres the info?

2021-09-22 19:44 UTC, lucawidergy commented on screens/HistoryScreen/index.js
> +  const renderText = text => (
you are not using it ?

2021-09-22 19:44 UTC, lucawidergy commented on screens/HomeScreen/index.js
> +  const NUMARRAY = ['7', '8', '9', '4', '5', '6', '1', '2', '3', '0'];
in constant file!

2021-09-22 19:44 UTC, lucawidergy commented on screens/HomeScreen/index.js
> +  const OPARRAY = ['+', '-', 'x', '/'];
idem

2021-09-22 19:44 UTC, lucawidergy commented on screens/HomeScreen/index.js
> +        <CalcButtons
here you can use the map!

2021-09-22 19:44 UTC, lucawidergy commented on utils.js
> +  const PRIORITYREGEX = /[-]?[.]?[0-9]*[.]?[0-9]+[/x][-]?[.]?[0-9]*[.]?[0-9]+/g;
what is priority regex? what does?

2021-09-22 19:44 UTC, lucawidergy commented on utils.js
> +  const SECONDARYREGEX = /[-]?[.]?[0-9]*[.]?[0-9]+[+-][-]?[.]?[0-9]*[.]?[0-9]+/g;
idem

2021-09-22 19:44 UTC, lucawidergy commented on styles.js
> +const styles = StyleSheet.create({
Do you ignore me? :C

2021-09-23 18:43 UTC, lucawidergy approved these changes
Good job!

2021-09-23 20:43 UTC, lcastelloni approved these changes
Great!!

2021-09-24 14:48 UTC, merged