Navigation
tvigon/widergy-mobile-training pull request #2
Opened 2021-09-15 22:16 UTC by tvigon

Card de navigation

2021-09-17 16:10 UTC, lcastelloni approved these changes
Great!

2021-09-17 16:13 UTC, lcastelloni requested changes

2021-09-17 16:13 UTC, lcastelloni commented on App.js
> +  return (
Move this component the components folder. The main component, in this case is App, should be the only one inside App.js file

2021-09-17 17:25 UTC, lucawidergy requested changes

2021-09-17 17:25 UTC, lucawidergy commented on App.js
> +function HistoryScreen({route, navigation}) {
no, we dont use funcion. Always we have arrow function!. Also this shoul be in other folder called screens and a folder for this screen inside

2021-09-17 17:25 UTC, lucawidergy commented on App.js
> +    <View style={{flex: 1}}>
put the style always in a style folder. we dont use inline styles

2021-09-17 17:25 UTC, lucawidergy commented on App.js
> +        <View style={[styles.row, styles.numButtons]}>
i think you forgot update this

2021-09-24 14:46 UTC, closed without merging

2021-09-24 14:46 UTC, tvigon commented
Navigation done. Deleted branch