Redux
tvigon/widergy-mobile-training pull request #3
Opened 2021-09-24 16:33 UTC by tvigon

Redux functionality applied. Must implement correction on ID's and reorder the structure of code.

2021-09-29 14:07 UTC, lcastelloni requested changes
Working great!

Just a few comments

If I write and operation, don't press "=" and hit save it saves an undefined expression in the store which results in an empty value.
If I do the same but have already written a valid expression it saves the older expression.
![imagen](https://user-images.githubusercontent.com/69810317/135284734-ac99e796-74ba-4cc2-a8c6-42bc931185ad.png)

2021-09-29 14:07 UTC, lcastelloni commented on redux/history/actions.js
> +  },
Why are we adding a random (and also very big) number to the index. We could just pass the state of history log to  addExpression and then calculate the length of that array. I know that when you deleted an expression the id of each expression cannot be calculated with the length of the history. Here we could do two things:

1. Add a new value inside history that increments each time you add an expression. If you have [id: 1,id: 2,id: 3, id: 4] and delete number for the next time that you add an expression it will look like this [id: 1,id: 2,id: 3, id: 5]
2. Each time that you delete and expression you remap the whole array to have an id that matches each element's index

2021-09-30 14:03 UTC, lucawidergy requested changes

2021-09-30 14:03 UTC, lucawidergy commented on App.js
> +    <Provider store={createStore(calcApp,
el create store deberia estar en un archivo llamado store dentro de la carpeta redux e importarlo desde ahi

2021-09-30 14:03 UTC, lucawidergy commented on redux/history/actions.js
> +    let max = 100000000000000000000;
en todo caso estas deberian ser constantes dentro de un archivo de cosntants

2021-09-30 14:03 UTC, lucawidergy commented on screens/HistoryScreen/components/historyList.js
> +  TouchableOpacity,
Aca hay imports que no usas, tratemos de ser prolijos

2021-09-30 14:03 UTC, lucawidergy commented on screens/HistoryScreen/components/historyList.js
> +const mapDispatchToProps = dispatch => {
no usamos mapDispatchToProps, para nosotros es mala palabra :P. no te aporta nada, y te esconde la que estas haciendo realmente por lo que termina siendo contraproducente

2021-09-30 14:03 UTC, lucawidergy commented on screens/HistoryScreen/components/historyList.js
> +const History = ({history, onHistoryClick, delClick}) => (
History o HistoryList?

2021-09-30 14:03 UTC, lucawidergy commented on screens/HistoryScreen/index.js
> +      <HistoryList />
Como opcion, tal vez convendria conectar solamente HistoryScreen al store y que HistoryList reciba por props el array de expresiones y la acciones necesarias. Asi el otro componente no queda atado a un solo tipo de historial y acciones

2021-09-30 14:35 UTC, tvigon commented on App.js
> +    <Provider store={createStore(calcApp,
done

2021-09-30 14:47 UTC, tvigon commented on redux/history/actions.js
> +    let max = 100000000000000000000;
done

2021-09-30 14:58 UTC, tvigon commented on screens/HistoryScreen/components/historyList.js
> +  TouchableOpacity,
done

2021-09-30 15:51 UTC, tvigon commented on screens/HistoryScreen/components/historyList.js
> +const mapDispatchToProps = dispatch => {
done

2021-09-30 15:57 UTC, tvigon commented on screens/HistoryScreen/components/historyList.js
> +const History = ({history, onHistoryClick, delClick}) => (
Le puse history porque es el nombre del reducer, pero como en mapStateToProps le paso state.history.historyLog deberia llamarse historyList. Done!

2021-09-30 16:26 UTC, tvigon commented on screens/HistoryScreen/index.js
> +      <HistoryList />
ya lo cambie! lo que deje igual es que historyList importe directamente las acciones de action creators, pero no esta mas conectado al store.

2021-10-01 14:48 UTC, lucawidergy approved these changes

2021-10-04 13:15 UTC, lcastelloni approved these changes
Great!

2021-10-04 14:14 UTC, merged